name: go-compile

on:
  push:
    branches: [ "master", "github-action-build" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.15

    - name: Build
      run: go build -o build -v ./src/main
    
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: main
        path: build/main
